### ISSUE TITLE
When is the next version released

### ISSUE THREAD

**Issue by flysk1** [phpmyadmin/phpmyadmin#17830]
I see 5.2.0 got many bugs and last update from 2022-05-10, when you decide to release new version sir?

**Comment by ibennetch** [comment]
Good question, I probably should do that soon. We don't have a strict schedule but it has been a while.

**Comment by flysk1** [comment]
Thank you, hope it release soon, all of us are waiting!

**Comment by williamdes** [comment]
Hi
You can install and try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) as it contains all the fixes made for the next version.
Please provide feedback if you find issues on this version :)

**Comment by flysk1** [comment]
Yes I know but we like automatic install with packed version more than develope version sir!

**Comment by williamdes** [comment]
> Yes I know but we like automatic install with packed version more than develope version sir!

Yeah I understand, by the way there is barely "no" difference with the next released version expect the changes that will be merged into 5.2 before the release is done

This also may be interesting to you: https://gist.github.com/williamdes/883f2158f17e9ed5a83d892ada56f5df

**Comment by flysk1** [comment]
Thank you but I hope you can release at least that version official for everyone, it's long time also, many people don't know snapshot or github, they just install automatic by commands!

**Comment by flysk1** [comment]
Any plan to release new official version sir?

**Comment by williamdes** [comment]
The [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) is also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots).

**Comment by williamdes** [comment]
This issues are "blocking" the release (https://github.com/phpmyadmin/phpmyadmin/milestone/273):
- [ ] #17833 (could be skipped but is problematic for some users)
- [ ] #17703 (showing the date picker when not needed is not very cool)
- [ ] #17778 (can be skipped, another date picker one)
- [ ] #17877 (⚠️ This one is important as most structure actions do not work correctly, the feedback shown to the user is wrong)
- [ ] #17340 (some data loss on a structure action, not many users should be affected)
- [ ] #17535 (⚠️ delete seems to manage to escape asking the user for confirmation)

**Comment by lostpetjp** [comment]
Hello.
I have used the latest version and am impressed with the significant improvements.
It is a hassle to download and build, but it is definitely worth it.

**Comment by williamdes** [comment]
> Hello. I have used the latest version and am impressed with the significant improvements. It is a hassle to download and build, but it is definitely worth it.

That's cool, thank you !
Why did you need to build ? I am curious if you can let us know :)
Because we provide a snapshot version: [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots)

**Comment by williamdes** [comment]
As I added into the TODO list sql-parser will need a new release, this is why I pushed 9a8452735c653ac0c35059ab8c93d5b90561fd8c to start testing the changes before the release

**Comment by lostpetjp** [comment]
I do not have the knowledge to do this, and I described "unzip and edit the config file" as build.
Sorry for the confusion with the confusing wording.
I always update phpMyAdmin this way.

**Comment by williamdes** [comment]
Hi @ibennetch 
I updated the TODO list: https://github.com/phpmyadmin/phpmyadmin/issues/17830#issuecomment-1313763138

And the next task to be done by you is to release sql-parser. I think that one day after that we can declare phpMyAdmin ready for a release.

To the known bugs in the release mail we should document the 2FA key issue: #17229

**Comment by williamdes** [comment]
New blocking one: https://github.com/phpmyadmin/phpmyadmin/issues/17931

**Comment by williamdes** [comment]
This is the last task near to be merged after testing: #17989   for WebAuthn support to fix #17229
cc @still-dreaming-1

**Comment by williamdes** [comment]
All users waiting for the next release should try the snapshot build with webauthn that just landed into 5.2.
See: https://github.com/phpmyadmin/phpmyadmin/issues/17229#issuecomment-1384622808

**Comment by williamdes** [comment]
Hi users,

Please test the the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)

This is important, the release should occur at the end of the month 🚀

**Comment by flysk1** [comment]
"This is important, the release should occur at the end of the month 🚀"
You mean today ?

**Comment by williamdes** [comment]
> "This is important, the release should occur at the end of the month 🚀" You mean today ?

I can not give any date but maybe @ibennetch can

**Comment by ibennetch** [comment]
I'm in the process of releasing version 5.2.1 right now, so it will be available as soon as it propagates across our CDN.

Thanks for your report and discussion.

**Comment by porg** [comment]
[Changelog](https://demo.phpmyadmin.net/master-config/index.php?route=/changelog): Shows 5.2.1 as released on 2023-02-07

Thanks!
